[package]
name = "rocket-server"
version = "0.1.0"
edition = "2018"
authors = ["Paul Tuck @pau1tuck"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"