[package]
name = "rocket-server"
version = "0.1.0"
edition = "2018"
authors = ["Paul Tuck @pau1tuck"]

[dependencies]
env_logger = "0.7"
log = "0.4"
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = [ "serve", "json" ] }